- alias: Bedroom Switch Top
  mode: single
  trigger:
    platform: state
    entity_id:
      - light.bedroom_top
    to: "on"
  action:
    - service: light.turn_off
      target:
        entity_id: light.bedroom_top
    - service: homeassistant.turn_on
      entity_id: scene.bedroom_bright

- alias: Bedroom Switch Bottom
  mode: single
  trigger:
    platform: state
    entity_id:
      - light.bedroom_bottom
    to: "on"
  action:
    - service: light.turn_off
      target:
        entity_id: light.bedroom_bottom
    - service: homeassistant.turn_on
      entity_id: scene.bedroom_off