- alias: "Dining Room Switch - On"
  trigger:
    device_id: c4a57a84729842b09704440c81a26ac8
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: turn_on
  action:
    service: scene.turn_on
    entity_id: scene.kitchen_on

- alias: "Dining Room Switch - Off"
  trigger:
    device_id: c4a57a84729842b09704440c81a26ac8
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: turn_off
  action:
    service: scene.turn_on
    entity_id: scene.kitchen_off

- alias: "Dining Room Switch - Up"
  trigger:
    device_id: c4a57a84729842b09704440c81a26ac8
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: dim_up
  action:
    service: cover.open_cover
    entity_id: cover.dining_room

- alias: "Dining Room Switch - Down"
  trigger:
    device_id: c4a57a84729842b09704440c81a26ac8
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: dim_down
  action:
    service: cover.close_cover
    entity_id: cover.dining_room
