- alias: Update notification
  trigger:
    - platform: state
      entity_id: binary_sensor.updater
      from: 'off'
      to: 'on'
  action:
    - service: notify.mobile_app_sams_iphone
      data_template:
        title: 'New Home Assistant Release'
        message: "Home Assistant {{ state_attr('binary_sensor.updater', 'newest_version') }} is now available!"
