- alias: Kitchen Switch - On
  trigger:
    device_id: 4518723e0e9a11eb98e9396f5762261c
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: turn_on
  action:
    service: scene.turn_on
    entity_id: scene.kitchen_on

- alias: Kitchen Switch - Off
  trigger:
    device_id: 4518723e0e9a11eb98e9396f5762261c
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: turn_off
  action:
    service: scene.turn_on
    entity_id: scene.kitchen_off

- alias: Kitchen Switch - Up
  trigger:
    device_id: 4518723e0e9a11eb98e9396f5762261c
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: dim_up
  action:
    service: cover.open_cover
    entity_id: cover.kitchen

- alias: Kitchen Switch - Down
  trigger:
    device_id: 4518723e0e9a11eb98e9396f5762261c
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: dim_down
  action:
    service: cover.close_cover
    entity_id: cover.kitchen
