# When a leak is detected, send a notification
- alias: Leak alerts
  trigger:
    - platform: device
      type: moist
      device_id: e45b28ba9f0b47718c62bac03b49b283
      entity_id: binary_sensor.dishwasher_leak
      domain: binary_sensor
  condition:
  action:
    - service: notify.mobile_app_sams_iphone
      data_template:
        title: '💦 Leak Detected'
        message: >-
          The dishwasher is leaking!
        data:
          push:
            sound:
              name: default
              critical: 1
              volume: 1.0
          apns_headers:
            apns-collapse-id: leak-alert
