- alias: "Living Room Switch - On"
  trigger:
    device_id: f9f52b9b0e9811eb933a8190df4e86f9
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: turn_on
  action:
    service: scene.turn_on
    entity_id: scene.living_room_on

- alias: "Living Room Switch - Off"
  trigger:
    device_id: f9f52b9b0e9811eb933a8190df4e86f9
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: turn_off
  action:
    service: scene.turn_on
    entity_id: scene.living_room_off

- alias: "Living Room Switch - Up"
  trigger:
    device_id: f9f52b9b0e9811eb933a8190df4e86f9
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: dim_up
  action:
    service: cover.open_cover
    entity_id: cover.living_room

- alias: "Living Room Switch - Down"
  trigger:
    device_id: f9f52b9b0e9811eb933a8190df4e86f9
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: turn_down
  action:
    service: cover.close_cover
    entity_id: cover.living_room
