- alias: Sunset
  trigger:
    platform: sun
    event: sunset
  action:
    service: homeassistant.turn_on
    entity_id: scene.sunset

- alias: Sunrise
  trigger:
    platform: sun
    event: sunrise
  action:
    service: homeassistant.turn_on
    entity_id: scene.sunrise

- alias: Late Night
  trigger:
    platform: time
    at: "12:00:00"
  condition:
    - condition: state
      entity_id: input_boolean.party_mode
      state: "off"
  action:
    service: homeassistant.turn_on
    entity_id: scene.late_night
