substitutions:
  name: upsy-desky-cc0990
  friendly_name: Upsy Desky
packages:
  tj_horner.upsy_desky: github://tjhorner/upsy-desky/firmware/stock.yaml@v1.1.1
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: YXTNs282vYWZDqTLm96XY/QMWipjJa2XS4V7goF5BDU=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
