name: Check Home Assistant configuration
on: [push, pull_request]
jobs:
  check:
    runs-on: ubuntu-latest
    container:
      image: homeassistant/amd64-homeassistant
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Copy secrets
        run: cp secrets_ci.yaml secrets.yaml
      - name: Check configuration
        run: hass --script check_config -c .
